# Generated by Django 4.0 on 2021-12-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tocsv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='upload',
            new_name='uploaded_file',
        ),
    ]
