# Generated by Django 4.0 on 2021-12-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocsv', '0002_rename_upload_uploadfile_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploaded/%Y/%m/$D/'),
        ),
    ]
