# Generated by Django 4.0 on 2021-12-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocsv', '0004_alter_uploadfile_uploaded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_file', models.FileField(blank=True, upload_to='download/')),
            ],
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='uploaded_file',
            field=models.FileField(upload_to='uploaded/'),
        ),
    ]
