# Generated by Django 4.0 on 2021-12-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tocsv', '0005_downloadfile_alter_uploadfile_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadfile',
            name='download_file',
            field=models.FileField(upload_to='download/'),
        ),
    ]
